### ISSUE TITLE
New release on the forge?

### ISSUE THREAD

**Issue by saz** [haraldsk/puppet-module-nfs#21]
I've tried to install your module from the forge, but I've ran into the error, reported in rodjek/librarian-puppet#71 due to the fact, that there wasn't a release since 2012.

Sadly, this module looks abandoned, is there any chance of a new release on the forge?

**Comment by tedivm** [comment]
@haraldsk can you do one last release of this module, even if it contains nothing but the updated readme file? That way people who find your module on the forge can easily find it's replacement.

@dwerder, thanks for forking and updating, it's very much appreciated!

**Comment by steflsd** [comment]
Is there an essential difference now between echocat/nfs and derdnne/nfs?

**Comment by dwerder** [comment]
https://github.com/derdanne/puppet-nfs/ is basically a complete rewrite, which seems to offer the same functionality (as far as I know). So I never tried it.

https://github.com/echocat/puppet-nfs/ is the original code with a lot of patches and enhancements.
