### ISSUE TITLE
no portmap service on ubuntu 14.04LTS (using 2.0 branch)

### ISSUE THREAD

**Issue by hdeadman** [haraldsk/puppet-module-nfs#35]
The dependency on the "portmap" service in nfs::client::debian::service didn't work for me on Ubuntu 14. I think the service dependency is now rpcbind. I am using the 2.0 branch b/c of a dependency cycle I was getting in the latest 1.x release. Not submitting a patch because I am not familiar with which versions of ubuntu use portmap and which use rpcbind.

**Comment by jskarpe** [comment]
+1

**Comment by dwerder** [comment]
This module has no mainenance anymore. Take a look at: https://github.com/echocat/puppet-nfs
